### ISSUE TITLE
Reopen an accidentally closed ticket

### ISSUE THREAD

**Issue by Matlek** [centuri-engineering/clicket#11]
I could not find a way to reopen an accidentally closed ticket. I there any way to do so?

**Comment by glyg** [comment]
I don't know, I'll look into it
G.

**Comment by glyg** [comment]
Ok, so if you go to My Tickets, and filter only the closed tickets, you can select one. Now if you add a comment to the closed ticket, it will be reopened automatically (that might be an effect of a recent bug fix).

Can you test that and close this issue if it works for you?

**Comment by Matlek** [comment]
Works well! Thanks!
