### ISSUE TITLE
Too many choices in "request_stage" and "procedure_stage"

### ISSUE THREAD

**Issue by Matlek** [centuri-engineering/clicket#12]
The current choices are the following:
-request_stage: new/in progress/pending/ready/finished/declined
-procedure_stage: consulting/maintenance/first contact/short/submitted/validated

A simpler possibility would be:
-request_stage: short/long 
-procedure_stage: update/pause/decline
And the details could be added manually (first contact/consulting...)

**Comment by glyg** [comment]
cc @BenDehap @thomas-vannier What do you think?

**Comment by glyg** [comment]
See #22
