### ISSUE TITLE
Issue uploading files

### ISSUE THREAD

**Issue by Matlek** [centuri-engineering/clicket#14]
Uploading files does not work anymore. I get the message "There was a problem uploading one or more of the files.".

**Comment by Matlek** [comment]
The problem seems to specifically occur on the ticket "CAD and machining of pieces for the 1st M-FIP device". I was able to upload files on other tickets.

**Comment by glyg** [comment]
Did you have this issue again?

**Comment by mathiaslec** [comment]
Yes I still get this message when trying to import JPG. Doing a screenshot of the images and uploading them as PNG seems to work. Does the issue comes from the format?

**Comment by glyg** [comment]
ha maybe, if the suffix is JPEG or JPG or something unusual?

**Comment by glyg** [comment]
here is a list of allowed file extensions:

https://github.com/centuri-engineering/clicket/blob/7faa94ee154dbd1b3cb974b707d4db3c12cc7eb9/setup.py#L27

Not sure if the capitalized version works,

**Comment by mathiaslec** [comment]
Thanks, that was the problem indeed. Works much better with lowercase!
