### ISSUE TITLE
MEP meeting 

### ISSUE THREAD

**Issue by glyg** [centuri-engineering/clicket#22]
* request_stage:

  - in progress : we're working on it ( <- new)
  - pending : waiting for input from the user ?
  - finished : the project is done ( <- ready)

* procedure_stage:

  - consulting first / consulting / maintenance ()
  - short
  - long (<- validated / submited)
  - declined (+)

* remove priority

**Comment by BDehapiot** [comment]
ok that is what we agreed for.
