### ISSUE TITLE
404 Error - File Not Found

### ISSUE THREAD

**Issue by mathiaslec** [centuri-engineering/clicket#28]
Old uploaded files cannot be read anymore.
For example the files uploaded on this ticket, the 13-11-2020 : https://centuri-engineering.univ-amu.fr/clicket/ticket_view/73/

**Comment by glyg** [comment]
Thanks for the report

Looks like they did not get moved at the same time as the base ... Can you confirm that this is the file?

![vu9dqb9t](https://user-images.githubusercontent.com/1426279/104751103-34868580-5755-11eb-9afd-2229d937d943.jpg)


If so I need to rebuild the docker image and tell it to copy the other ones there, but they are not lost. I'll fix this on Monday if it's not too urgent...

**Comment by mathiaslec** [comment]
Yes it is the first uploaded file on the ticket. Ok thanks! No worries, I am not on a hurry.

**Comment by glyg** [comment]
I re-uploaded the files, they are visible now
